Parameters:
  AssetParameters72642eda23c11cfca16fd966ecbd9e45e25c365592f951d4d64865c445f31cafS3BucketB4F52C12:
    Type: String
    Description: S3 bucket for asset "72642eda23c11cfca16fd966ecbd9e45e25c365592f951d4d64865c445f31caf"
  AssetParameters72642eda23c11cfca16fd966ecbd9e45e25c365592f951d4d64865c445f31cafS3VersionKey0D816B20:
    Type: String
    Description: S3 key for asset version "72642eda23c11cfca16fd966ecbd9e45e25c365592f951d4d64865c445f31caf"
  AssetParameters72642eda23c11cfca16fd966ecbd9e45e25c365592f951d4d64865c445f31cafArtifactHash8B231C83:
    Type: String
    Description: Artifact hash for asset "72642eda23c11cfca16fd966ecbd9e45e25c365592f951d4d64865c445f31caf"
Resources:
  HelloGoServerLambdaFnServiceRole28011915:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: InfraStack/HelloGoServerLambdaFn/ServiceRole/Resource
  HelloGoServerLambdaFn9A9C4250:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters72642eda23c11cfca16fd966ecbd9e45e25c365592f951d4d64865c445f31cafS3BucketB4F52C12
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters72642eda23c11cfca16fd966ecbd9e45e25c365592f951d4d64865c445f31cafS3VersionKey0D816B20
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters72642eda23c11cfca16fd966ecbd9e45e25c365592f951d4d64865c445f31cafS3VersionKey0D816B20
      Role:
        Fn::GetAtt:
          - HelloGoServerLambdaFnServiceRole28011915
          - Arn
      Handler: main
      Runtime: go1.x
    DependsOn:
      - HelloGoServerLambdaFnServiceRole28011915
    Metadata:
      aws:cdk:path: InfraStack/HelloGoServerLambdaFn/Resource
  HelloGoServerLambdaFnEndpoint02CC1A11:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: HelloGoServerLambdaFnEndpoint
    Metadata:
      aws:cdk:path: InfraStack/HelloGoServerLambdaFnEndpoint/Resource
  HelloGoServerLambdaFnEndpointCloudWatchRoleBA1AB6E6:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: InfraStack/HelloGoServerLambdaFnEndpoint/CloudWatchRole/Resource
  HelloGoServerLambdaFnEndpointAccount24289C66:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - HelloGoServerLambdaFnEndpointCloudWatchRoleBA1AB6E6
          - Arn
    DependsOn:
      - HelloGoServerLambdaFnEndpoint02CC1A11
    Metadata:
      aws:cdk:path: InfraStack/HelloGoServerLambdaFnEndpoint/Account
  HelloGoServerLambdaFnEndpointDeployment1BF58C33162d2526855a22e0d8342a5aa830332c:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: HelloGoServerLambdaFnEndpoint02CC1A11
      Description: Automatically created by the RestApi construct
    DependsOn:
      - HelloGoServerLambdaFnEndpointproxyANYC78A2E0A
      - HelloGoServerLambdaFnEndpointproxy15DB6F73
      - HelloGoServerLambdaFnEndpointANYDF90CB8A
    Metadata:
      aws:cdk:path: InfraStack/HelloGoServerLambdaFnEndpoint/Deployment/Resource
  HelloGoServerLambdaFnEndpointDeploymentStageprodCCCB5C45:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: HelloGoServerLambdaFnEndpoint02CC1A11
      DeploymentId:
        Ref: HelloGoServerLambdaFnEndpointDeployment1BF58C33162d2526855a22e0d8342a5aa830332c
      StageName: prod
    DependsOn:
      - HelloGoServerLambdaFnEndpointAccount24289C66
    Metadata:
      aws:cdk:path: InfraStack/HelloGoServerLambdaFnEndpoint/DeploymentStage.prod/Resource
  HelloGoServerLambdaFnEndpointproxy15DB6F73:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - HelloGoServerLambdaFnEndpoint02CC1A11
          - RootResourceId
      PathPart: "{proxy+}"
      RestApiId:
        Ref: HelloGoServerLambdaFnEndpoint02CC1A11
    Metadata:
      aws:cdk:path: InfraStack/HelloGoServerLambdaFnEndpoint/Default/{proxy+}/Resource
  HelloGoServerLambdaFnEndpointproxyANYApiPermissionInfraStackHelloGoServerLambdaFnEndpoint672DEFD4ANYproxy8220D896:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - HelloGoServerLambdaFn9A9C4250
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: HelloGoServerLambdaFnEndpoint02CC1A11
            - /
            - Ref: HelloGoServerLambdaFnEndpointDeploymentStageprodCCCB5C45
            - /*/*
    Metadata:
      aws:cdk:path: InfraStack/HelloGoServerLambdaFnEndpoint/Default/{proxy+}/ANY/ApiPermission.InfraStackHelloGoServerLambdaFnEndpoint672DEFD4.ANY..{proxy+}
  HelloGoServerLambdaFnEndpointproxyANYApiPermissionTestInfraStackHelloGoServerLambdaFnEndpoint672DEFD4ANYproxyCCE3DE61:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - HelloGoServerLambdaFn9A9C4250
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: HelloGoServerLambdaFnEndpoint02CC1A11
            - /test-invoke-stage/*/*
    Metadata:
      aws:cdk:path: InfraStack/HelloGoServerLambdaFnEndpoint/Default/{proxy+}/ANY/ApiPermission.Test.InfraStackHelloGoServerLambdaFnEndpoint672DEFD4.ANY..{proxy+}
  HelloGoServerLambdaFnEndpointproxyANYC78A2E0A:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Ref: HelloGoServerLambdaFnEndpointproxy15DB6F73
      RestApiId:
        Ref: HelloGoServerLambdaFnEndpoint02CC1A11
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - HelloGoServerLambdaFn9A9C4250
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: InfraStack/HelloGoServerLambdaFnEndpoint/Default/{proxy+}/ANY/Resource
  HelloGoServerLambdaFnEndpointANYApiPermissionInfraStackHelloGoServerLambdaFnEndpoint672DEFD4ANY17F5BAE9:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - HelloGoServerLambdaFn9A9C4250
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: HelloGoServerLambdaFnEndpoint02CC1A11
            - /
            - Ref: HelloGoServerLambdaFnEndpointDeploymentStageprodCCCB5C45
            - /*/
    Metadata:
      aws:cdk:path: InfraStack/HelloGoServerLambdaFnEndpoint/Default/ANY/ApiPermission.InfraStackHelloGoServerLambdaFnEndpoint672DEFD4.ANY..
  HelloGoServerLambdaFnEndpointANYApiPermissionTestInfraStackHelloGoServerLambdaFnEndpoint672DEFD4ANY34FA0173:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - HelloGoServerLambdaFn9A9C4250
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: HelloGoServerLambdaFnEndpoint02CC1A11
            - /test-invoke-stage/*/
    Metadata:
      aws:cdk:path: InfraStack/HelloGoServerLambdaFnEndpoint/Default/ANY/ApiPermission.Test.InfraStackHelloGoServerLambdaFnEndpoint672DEFD4.ANY..
  HelloGoServerLambdaFnEndpointANYDF90CB8A:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Fn::GetAtt:
          - HelloGoServerLambdaFnEndpoint02CC1A11
          - RootResourceId
      RestApiId:
        Ref: HelloGoServerLambdaFnEndpoint02CC1A11
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - HelloGoServerLambdaFn9A9C4250
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: InfraStack/HelloGoServerLambdaFnEndpoint/Default/ANY/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/02PwU7DMAyGn2X3zKMq2pluaCcQVXmCkJqStUmq2GFUUd+dJmWoJ3+2ks+/Cygej/Cwe5I32qu2P0TlPEJ8Z6l6UREhL9hp24mzs8Q+KBbnT1tLLw0y+tS8BR5DHjdILniFiZf3rWbt7CySPFK5l8lHkLWCSjgF1SOfJKEYpPloJcRLsCp9SoYt1+iNJso6LQ3Exg15TarLhlF3kvEmJ4gvWbVE4WrUf6nuWCnlgmXxjOPgJoM2x9506drsXeF+UM5Ye/czbU/851fkL9em0UrzPAvrWoQrHb6LIxQlFLsrab33y3ZtEJq1/gKUhOzegAEAAA==
    Metadata:
      aws:cdk:path: InfraStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  HelloGoServerLambdaFnEndpoint58254B97:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: HelloGoServerLambdaFnEndpoint02CC1A11
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: HelloGoServerLambdaFnEndpointDeploymentStageprodCCCB5C45
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

